### ISSUE TITLE
indimite map downloading if you put new pickture white downloading 

### ISSUE THREAD

**Issue by JGTB0PL** [rebane2001/mapartcraft#130]
if you upload a photo while downloading maps.dat it will stop this proces and start it for image that you uploaded to website

it will aply same settings (at least i thing)

**Comment by rebane2001** [comment]
I have no clue what this issue is about

**Comment by SelfAdjointOperator** [comment]
Managed to figure out what this issue was saying. In old MapartCraft this can happen if you uploaded an image while downloading multiple 1x1 mapdats lol
![2021-07-17_00 43 57](https://user-images.githubusercontent.com/66702639/126018264-0082d6b2-0fb3-49a7-88a3-4b3a44f45008.png)
Really rare / good timing I guess. This is no longer an issue since the React refactor as the entire canvas data is passed to the NBT worker in one go. Uploading an image whilst mapdats for a previous image are being generated terminates the worker too.
