### ISSUE TITLE
Warped Hyphae no longer a purple colour on minecraft map

### ISSUE THREAD

**Issue by DonutLover15** [rebane2001/mapartcraft#140]
Warped Hyphae now comes up as a light blue colour on the minecraft map.

**Comment by calebschieck** [comment]
In 1.16.4 it looks correct to the website color for me.
![image](https://user-images.githubusercontent.com/17679946/113806367-02167400-9717-11eb-917c-7734bc57429e.png)

**Comment by SelfAdjointOperator** [comment]
Just tested 1.16.5, MapartCraft has the correct tones for all 1.16.5 colours
![116Colours](https://user-images.githubusercontent.com/66702639/114587201-54a6e180-9c7d-11eb-9da2-1ca660398ebf.png)

**Comment by xteeth** [comment]
![Screenshot (2383)](https://user-images.githubusercontent.com/83135638/115968674-94cc5680-a4fe-11eb-88b5-c5a5d5e821b3.png)
I think I might have found the issue! If there was any chance you were using Warped Stems instead of Warped Hyphae, they will *not* be the same colour as the Hyphae, they'll be blue regardless of directional facing. Tested this in 1.16.4 and 1.16.5 Vanilla and both versions have Hyphae as purple and Stems as blue.
