### ISSUE TITLE
Transparent Maps Images Get "Mutilated"

### ISSUE THREAD

**Issue by CrispyMiner** [rebane2001/mapartcraft#159]
Trying to turn a transparent image into multiple maps (even if the image dimensions are exact). can cause it to glitch and make the image horribly "mutilated"
![2021-04-23_16 17 40](https://user-images.githubusercontent.com/18730519/115926481-e918fd00-a450-11eb-8fbb-c27189f89cf2.png)
![mariokart](https://user-images.githubusercontent.com/18730519/115926493-ee764780-a450-11eb-9944-f32db588efe1.png)

**Comment by markaabo** [comment]
I have the same problem, it seems like all maps exported to map.dat files have the same "physical" location for minecraft so all the maps seems to be stacked above eachother, so the map your trying to show e.g. "map_11" gets shown on top but all other maps gets stacked below "map_11"

**Comment by rebane2001** [comment]
If you refresh the page and import the image first time without changing anything it will work fine. It's an annoying workaround but it works for now.

**Comment by markaabo** [comment]
> 
> 
> If you refresh the page and import the image first time without changing anything it will work fine. It's an annoying workaround but it works for now.

I cannot get it to work like your said, if i refresh and click download it says "Select blocks before downloading!", then if i select "Everything" in blocks it pops up with "An error has occured! This is most likely because you are using a privacy-enhanced browser (such as Brave). Please turn off protections/shields or use a different browser such as Chrome or Firefox."

The error does not come up if i do it normally but then the maps stack on eachother, also i have disabled security stuff in firefox and added the website to exclutions from everything that has security or adblocking...

**Comment by rebane2001** [comment]
Firefox probably messes something up with a refresh. Do the same thing but instead of refreshing close the tab and open MapartCraft in a new tab.

**Comment by markaabo** [comment]
> 
> 
> Firefox probably messes something up with a refresh. Do the same thing but instead of refreshing close the tab and open MapartCraft in a new tab.

That seems to have fixed it, tho i found that the map im trying to create is 3x1, and to get it to work i need to cut it into 3 different image files that are 1x1 and export 1 at a time. Thank you for the help, hope it can be fixed in the future so theirs no need to reopen and cut to 1x1 :)

**Comment by ux01** [comment]
Same problem. This is triggered when you replace one map with another (the first map appears under the layer of the second map). And also when using "Map size" - each next map has all the previous ones under it.

And if the first problem is solved by rebooting (which is inconvenient, because the parameters are reset), then I did not find a solution for the second one. Except that you can manually divide it into 1x1 maps...

Cent browser (Chromium).

**Comment by rebane2001** [comment]
Fixed in #168
